<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SurchargeType', 'doctrine');

/**
 * BaseSurchargeType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property Doctrine_Collection $Surcharge
 * @property Doctrine_Collection $Surcharge_4
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getType()        Returns the current record's "type" value
 * @method Doctrine_Collection getSurcharge()   Returns the current record's "Surcharge" collection
 * @method Doctrine_Collection getSurcharge4()  Returns the current record's "Surcharge_4" collection
 * @method SurchargeType       setId()          Sets the current record's "id" value
 * @method SurchargeType       setType()        Sets the current record's "type" value
 * @method SurchargeType       setSurcharge()   Sets the current record's "Surcharge" collection
 * @method SurchargeType       setSurcharge4()  Sets the current record's "Surcharge_4" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSurchargeType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('surcharge_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Surcharge', array(
             'local' => 'id',
             'foreign' => 'surcharge_type_id'));

        $this->hasMany('Surcharge as Surcharge_4', array(
             'local' => 'id',
             'foreign' => 'surcharge_type_id'));
    }
}