<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CourierDiscount', 'doctrine');

/**
 * BaseCourierDiscount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $courier_id
 * @property integer $discount
 * @property Courier $Courier
 * @property Courier $Courier_2
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method integer         getCourierId()  Returns the current record's "courier_id" value
 * @method integer         getDiscount()   Returns the current record's "discount" value
 * @method Courier         getCourier()    Returns the current record's "Courier" value
 * @method Courier         getCourier2()   Returns the current record's "Courier_2" value
 * @method CourierDiscount setId()         Sets the current record's "id" value
 * @method CourierDiscount setCourierId()  Sets the current record's "courier_id" value
 * @method CourierDiscount setDiscount()   Sets the current record's "discount" value
 * @method CourierDiscount setCourier()    Sets the current record's "Courier" value
 * @method CourierDiscount setCourier2()   Sets the current record's "Courier_2" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourierDiscount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('courier_discount');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('courier_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('discount', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Courier', array(
             'local' => 'courier_id',
             'foreign' => 'id'));

        $this->hasOne('Courier as Courier_2', array(
             'local' => 'courier_id',
             'foreign' => 'id'));
    }
}