<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DeliveryType', 'doctrine');

/**
 * BaseDeliveryType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property Doctrine_Collection $PackageDetail
 * @property Doctrine_Collection $PackageDetail_2
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getType()            Returns the current record's "type" value
 * @method Doctrine_Collection getPackageDetail()   Returns the current record's "PackageDetail" collection
 * @method Doctrine_Collection getPackageDetail2()  Returns the current record's "PackageDetail_2" collection
 * @method DeliveryType        setId()              Sets the current record's "id" value
 * @method DeliveryType        setType()            Sets the current record's "type" value
 * @method DeliveryType        setPackageDetail()   Sets the current record's "PackageDetail" collection
 * @method DeliveryType        setPackageDetail2()  Sets the current record's "PackageDetail_2" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeliveryType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('delivery_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PackageDetail', array(
             'local' => 'id',
             'foreign' => 'delivery_type_id'));

        $this->hasMany('PackageDetail as PackageDetail_2', array(
             'local' => 'id',
             'foreign' => 'delivery_type_id'));
    }
}