<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StreetType', 'doctrine');

/**
 * BaseStreetType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * 
 * @method integer    getId()   Returns the current record's "id" value
 * @method string     getType() Returns the current record's "type" value
 * @method StreetType setId()   Sets the current record's "id" value
 * @method StreetType setType() Sets the current record's "type" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStreetType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('street_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}