<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServiceLevel', 'doctrine');

/**
 * BaseServiceLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $courier_id
 * @property integer $type_id
 * @property integer $is_enabled
 * @property Courier $Courier
 * @property Courier $Courier_2
 * @property ServiceLevelType $ServiceLevelType
 * @property ServiceLevelType $ServiceLevelType_4
 * @property Doctrine_Collection $ServiceAddon
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getCourierId()          Returns the current record's "courier_id" value
 * @method integer             getTypeId()             Returns the current record's "type_id" value
 * @method integer             getIsEnabled()          Returns the current record's "is_enabled" value
 * @method Courier             getCourier()            Returns the current record's "Courier" value
 * @method Courier             getCourier2()           Returns the current record's "Courier_2" value
 * @method ServiceLevelType    getServiceLevelType()   Returns the current record's "ServiceLevelType" value
 * @method ServiceLevelType    getServiceLevelType4()  Returns the current record's "ServiceLevelType_4" value
 * @method Doctrine_Collection getServiceAddon()       Returns the current record's "ServiceAddon" collection
 * @method ServiceLevel        setId()                 Sets the current record's "id" value
 * @method ServiceLevel        setCourierId()          Sets the current record's "courier_id" value
 * @method ServiceLevel        setTypeId()             Sets the current record's "type_id" value
 * @method ServiceLevel        setIsEnabled()          Sets the current record's "is_enabled" value
 * @method ServiceLevel        setCourier()            Sets the current record's "Courier" value
 * @method ServiceLevel        setCourier2()           Sets the current record's "Courier_2" value
 * @method ServiceLevel        setServiceLevelType()   Sets the current record's "ServiceLevelType" value
 * @method ServiceLevel        setServiceLevelType4()  Sets the current record's "ServiceLevelType_4" value
 * @method ServiceLevel        setServiceAddon()       Sets the current record's "ServiceAddon" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiceLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service_level');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('courier_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('is_enabled', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Courier', array(
             'local' => 'courier_id',
             'foreign' => 'id'));

        $this->hasOne('Courier as Courier_2', array(
             'local' => 'courier_id',
             'foreign' => 'id'));

        $this->hasOne('ServiceLevelType', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasOne('ServiceLevelType as ServiceLevelType_4', array(
             'local' => 'type_id',
             'foreign' => 'id'));

        $this->hasMany('ServiceAddon', array(
             'local' => 'type_id',
             'foreign' => 'service_level_type_id'));
    }
}