<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServiceLevelType', 'doctrine');

/**
 * BaseServiceLevelType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $hours
 * @property Doctrine_Collection $PackageDetail
 * @property Doctrine_Collection $PackageDetail_4
 * @property Doctrine_Collection $PackageDetail_7
 * @property Doctrine_Collection $ServiceLevel
 * @property Doctrine_Collection $ServiceLevel_4
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getType()            Returns the current record's "type" value
 * @method string              getHours()           Returns the current record's "hours" value
 * @method Doctrine_Collection getPackageDetail()   Returns the current record's "PackageDetail" collection
 * @method Doctrine_Collection getPackageDetail4()  Returns the current record's "PackageDetail_4" collection
 * @method Doctrine_Collection getPackageDetail7()  Returns the current record's "PackageDetail_7" collection
 * @method Doctrine_Collection getServiceLevel()    Returns the current record's "ServiceLevel" collection
 * @method Doctrine_Collection getServiceLevel4()   Returns the current record's "ServiceLevel_4" collection
 * @method ServiceLevelType    setId()              Sets the current record's "id" value
 * @method ServiceLevelType    setType()            Sets the current record's "type" value
 * @method ServiceLevelType    setHours()           Sets the current record's "hours" value
 * @method ServiceLevelType    setPackageDetail()   Sets the current record's "PackageDetail" collection
 * @method ServiceLevelType    setPackageDetail4()  Sets the current record's "PackageDetail_4" collection
 * @method ServiceLevelType    setPackageDetail7()  Sets the current record's "PackageDetail_7" collection
 * @method ServiceLevelType    setServiceLevel()    Sets the current record's "ServiceLevel" collection
 * @method ServiceLevelType    setServiceLevel4()   Sets the current record's "ServiceLevel_4" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiceLevelType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service_level_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('hours', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PackageDetail', array(
             'local' => 'id',
             'foreign' => 'service_level_type_id'));

        $this->hasMany('PackageDetail as PackageDetail_4', array(
             'local' => 'id',
             'foreign' => 'service_level_type_id'));

        $this->hasMany('PackageDetail as PackageDetail_7', array(
             'local' => 'id',
             'foreign' => 'service_level_type_id'));

        $this->hasMany('ServiceLevel', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $this->hasMany('ServiceLevel as ServiceLevel_4', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}