<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Package', 'doctrine');

/**
 * BasePackage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $package_code
 * @property integer $courier_id
 * @property integer $client_id
 * @property integer $from_address_id
 * @property integer $to_address_id
 * @property integer $status_id
 * @property integer $detail_id
 * @property decimal $partner_price
 * @property decimal $partner_tax
 * @property decimal $price
 * @property decimal $tax
 * @property Client $Client
 * @property Courier $Courier
 * @property PackageDetail $PackageDetail
 * @property Address $Address
 * @property Client $Client_5
 * @property Address $Address_6
 * @property Address $Address_7
 * @property PackageStatus $PackageStatus
 * @property PackageDetail $PackageDetail_9
 * @property Courier $Courier_10
 * @property PackageStatus $PackageStatus_11
 * @property Address $Address_12
 * @property Doctrine_Collection $PackagePayment
 * @property Doctrine_Collection $PackagePayment_3
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getPackageCode()      Returns the current record's "package_code" value
 * @method integer             getCourierId()        Returns the current record's "courier_id" value
 * @method integer             getClientId()         Returns the current record's "client_id" value
 * @method integer             getFromAddressId()    Returns the current record's "from_address_id" value
 * @method integer             getToAddressId()      Returns the current record's "to_address_id" value
 * @method integer             getStatusId()         Returns the current record's "status_id" value
 * @method integer             getDetailId()         Returns the current record's "detail_id" value
 * @method decimal             getPartnerPrice()     Returns the current record's "partner_price" value
 * @method decimal             getPartnerTax()       Returns the current record's "partner_tax" value
 * @method decimal             getPrice()            Returns the current record's "price" value
 * @method decimal             getTax()              Returns the current record's "tax" value
 * @method Client              getClient()           Returns the current record's "Client" value
 * @method Courier             getCourier()          Returns the current record's "Courier" value
 * @method PackageDetail       getPackageDetail()    Returns the current record's "PackageDetail" value
 * @method Address             getAddress()          Returns the current record's "Address" value
 * @method Client              getClient5()          Returns the current record's "Client_5" value
 * @method Address             getAddress6()         Returns the current record's "Address_6" value
 * @method Address             getAddress7()         Returns the current record's "Address_7" value
 * @method PackageStatus       getPackageStatus()    Returns the current record's "PackageStatus" value
 * @method PackageDetail       getPackageDetail9()   Returns the current record's "PackageDetail_9" value
 * @method Courier             getCourier10()        Returns the current record's "Courier_10" value
 * @method PackageStatus       getPackageStatus11()  Returns the current record's "PackageStatus_11" value
 * @method Address             getAddress12()        Returns the current record's "Address_12" value
 * @method Doctrine_Collection getPackagePayment()   Returns the current record's "PackagePayment" collection
 * @method Doctrine_Collection getPackagePayment3()  Returns the current record's "PackagePayment_3" collection
 * @method Package             setId()               Sets the current record's "id" value
 * @method Package             setPackageCode()      Sets the current record's "package_code" value
 * @method Package             setCourierId()        Sets the current record's "courier_id" value
 * @method Package             setClientId()         Sets the current record's "client_id" value
 * @method Package             setFromAddressId()    Sets the current record's "from_address_id" value
 * @method Package             setToAddressId()      Sets the current record's "to_address_id" value
 * @method Package             setStatusId()         Sets the current record's "status_id" value
 * @method Package             setDetailId()         Sets the current record's "detail_id" value
 * @method Package             setPartnerPrice()     Sets the current record's "partner_price" value
 * @method Package             setPartnerTax()       Sets the current record's "partner_tax" value
 * @method Package             setPrice()            Sets the current record's "price" value
 * @method Package             setTax()              Sets the current record's "tax" value
 * @method Package             setClient()           Sets the current record's "Client" value
 * @method Package             setCourier()          Sets the current record's "Courier" value
 * @method Package             setPackageDetail()    Sets the current record's "PackageDetail" value
 * @method Package             setAddress()          Sets the current record's "Address" value
 * @method Package             setClient5()          Sets the current record's "Client_5" value
 * @method Package             setAddress6()         Sets the current record's "Address_6" value
 * @method Package             setAddress7()         Sets the current record's "Address_7" value
 * @method Package             setPackageStatus()    Sets the current record's "PackageStatus" value
 * @method Package             setPackageDetail9()   Sets the current record's "PackageDetail_9" value
 * @method Package             setCourier10()        Sets the current record's "Courier_10" value
 * @method Package             setPackageStatus11()  Sets the current record's "PackageStatus_11" value
 * @method Package             setAddress12()        Sets the current record's "Address_12" value
 * @method Package             setPackagePayment()   Sets the current record's "PackagePayment" collection
 * @method Package             setPackagePayment3()  Sets the current record's "PackagePayment_3" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('package_code', 'string', 48, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 48,
             ));
        $this->hasColumn('courier_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('client_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('from_address_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('to_address_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('status_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('detail_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('partner_price', 'decimal', 7, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             'scale' => '2',
             ));
        $this->hasColumn('partner_tax', 'decimal', 7, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             'scale' => '2',
             ));
        $this->hasColumn('price', 'decimal', 7, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             'scale' => '2',
             ));
        $this->hasColumn('tax', 'decimal', 7, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Courier', array(
             'local' => 'courier_id',
             'foreign' => 'id'));

        $this->hasOne('PackageDetail', array(
             'local' => 'detail_id',
             'foreign' => 'id'));

        $this->hasOne('Address', array(
             'local' => 'from_address_id',
             'foreign' => 'id'));

        $this->hasOne('Client as Client_5', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Address as Address_6', array(
             'local' => 'from_address_id',
             'foreign' => 'id'));

        $this->hasOne('Address as Address_7', array(
             'local' => 'to_address_id',
             'foreign' => 'id'));

        $this->hasOne('PackageStatus', array(
             'local' => 'status_id',
             'foreign' => 'id'));

        $this->hasOne('PackageDetail as PackageDetail_9', array(
             'local' => 'detail_id',
             'foreign' => 'id'));

        $this->hasOne('Courier as Courier_10', array(
             'local' => 'courier_id',
             'foreign' => 'id'));

        $this->hasOne('PackageStatus as PackageStatus_11', array(
             'local' => 'status_id',
             'foreign' => 'id'));

        $this->hasOne('Address as Address_12', array(
             'local' => 'to_address_id',
             'foreign' => 'id'));

        $this->hasMany('PackagePayment', array(
             'local' => 'id',
             'foreign' => 'package_id'));

        $this->hasMany('PackagePayment as PackagePayment_3', array(
             'local' => 'id',
             'foreign' => 'package_id'));
    }
}