<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MigrationVersion', 'doctrine');

/**
 * BaseMigrationVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $version
 * 
 * @method integer          getId()      Returns the current record's "id" value
 * @method integer          getVersion() Returns the current record's "version" value
 * @method MigrationVersion setId()      Sets the current record's "id" value
 * @method MigrationVersion setVersion() Sets the current record's "version" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMigrationVersion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('migration_version');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('version', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}