<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('WeightPrice', 'doctrine');

/**
 * BaseWeightPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $weight_start
 * @property integer $weight_end
 * @property integer $price_level_id
 * @property integer $price_type_id
 * @property integer $weight_type_id
 * @property decimal $price
 * @property WeightType $WeightType
 * @property PriceLevel $PriceLevel
 * @property PriceType $PriceType
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method integer     getWeightStart()    Returns the current record's "weight_start" value
 * @method integer     getWeightEnd()      Returns the current record's "weight_end" value
 * @method integer     getPriceLevelId()   Returns the current record's "price_level_id" value
 * @method integer     getPriceTypeId()    Returns the current record's "price_type_id" value
 * @method integer     getWeightTypeId()   Returns the current record's "weight_type_id" value
 * @method decimal     getPrice()          Returns the current record's "price" value
 * @method WeightType  getWeightType()     Returns the current record's "WeightType" value
 * @method PriceLevel  getPriceLevel()     Returns the current record's "PriceLevel" value
 * @method PriceType   getPriceType()      Returns the current record's "PriceType" value
 * @method WeightPrice setId()             Sets the current record's "id" value
 * @method WeightPrice setWeightStart()    Sets the current record's "weight_start" value
 * @method WeightPrice setWeightEnd()      Sets the current record's "weight_end" value
 * @method WeightPrice setPriceLevelId()   Sets the current record's "price_level_id" value
 * @method WeightPrice setPriceTypeId()    Sets the current record's "price_type_id" value
 * @method WeightPrice setWeightTypeId()   Sets the current record's "weight_type_id" value
 * @method WeightPrice setPrice()          Sets the current record's "price" value
 * @method WeightPrice setWeightType()     Sets the current record's "WeightType" value
 * @method WeightPrice setPriceLevel()     Sets the current record's "PriceLevel" value
 * @method WeightPrice setPriceType()      Sets the current record's "PriceType" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWeightPrice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('weight_price');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('weight_start', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('weight_end', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('price_level_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('price_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('weight_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('price', 'decimal', 7, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WeightType', array(
             'local' => 'weight_type_id',
             'foreign' => 'id'));

        $this->hasOne('PriceLevel', array(
             'local' => 'price_level_id',
             'foreign' => 'id'));

        $this->hasOne('PriceType', array(
             'local' => 'price_type_id',
             'foreign' => 'id'));
    }
}