<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SmsIncoming', 'doctrine');

/**
 * BaseSmsIncoming
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $carrier
 * @property string $toa
 * @property string $smsc
 * @property timestamp $sent_on
 * @property timestamp $received_on
 * @property string $imsi
 * @property integer $length
 * @property string $text
 * @property integer $reply_required
 * @property timestamp $replied_on
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method string      getCarrier()        Returns the current record's "carrier" value
 * @method string      getToa()            Returns the current record's "toa" value
 * @method string      getSmsc()           Returns the current record's "smsc" value
 * @method timestamp   getSentOn()         Returns the current record's "sent_on" value
 * @method timestamp   getReceivedOn()     Returns the current record's "received_on" value
 * @method string      getImsi()           Returns the current record's "imsi" value
 * @method integer     getLength()         Returns the current record's "length" value
 * @method string      getText()           Returns the current record's "text" value
 * @method integer     getReplyRequired()  Returns the current record's "reply_required" value
 * @method timestamp   getRepliedOn()      Returns the current record's "replied_on" value
 * @method SmsIncoming setId()             Sets the current record's "id" value
 * @method SmsIncoming setCarrier()        Sets the current record's "carrier" value
 * @method SmsIncoming setToa()            Sets the current record's "toa" value
 * @method SmsIncoming setSmsc()           Sets the current record's "smsc" value
 * @method SmsIncoming setSentOn()         Sets the current record's "sent_on" value
 * @method SmsIncoming setReceivedOn()     Sets the current record's "received_on" value
 * @method SmsIncoming setImsi()           Sets the current record's "imsi" value
 * @method SmsIncoming setLength()         Sets the current record's "length" value
 * @method SmsIncoming setText()           Sets the current record's "text" value
 * @method SmsIncoming setReplyRequired()  Sets the current record's "reply_required" value
 * @method SmsIncoming setRepliedOn()      Sets the current record's "replied_on" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsIncoming extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms_incoming');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('carrier', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('toa', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('smsc', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('sent_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('received_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('imsi', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('length', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('reply_required', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('replied_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}