<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PackageDetail', 'doctrine');

/**
 * BasePackageDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $ready_time
 * @property string $ready_date
 * @property integer $num_pieces
 * @property decimal $weight
 * @property integer $weight_type_id
 * @property string $reference
 * @property integer $package_type_id
 * @property integer $service_level_type_id
 * @property integer $delivery_type_id
 * @property integer $round_trip
 * @property string $instructions
 * @property string $sender_phone
 * @property string $sender_contact
 * @property string $phone
 * @property string $contact
 * @property string $signed_by
 * @property timestamp $last_updated
 * @property DeliveryType $DeliveryType
 * @property DeliveryType $DeliveryType_2
 * @property ServiceLevelType $ServiceLevelType
 * @property ServiceLevelType $ServiceLevelType_4
 * @property PackageType $PackageType
 * @property WeightType $WeightType
 * @property ServiceLevelType $ServiceLevelType_7
 * @property Doctrine_Collection $Package
 * @property Doctrine_Collection $Package_9
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getReadyTime()             Returns the current record's "ready_time" value
 * @method string              getReadyDate()             Returns the current record's "ready_date" value
 * @method integer             getNumPieces()             Returns the current record's "num_pieces" value
 * @method decimal             getWeight()                Returns the current record's "weight" value
 * @method integer             getWeightTypeId()          Returns the current record's "weight_type_id" value
 * @method string              getReference()             Returns the current record's "reference" value
 * @method integer             getPackageTypeId()         Returns the current record's "package_type_id" value
 * @method integer             getServiceLevelTypeId()    Returns the current record's "service_level_type_id" value
 * @method integer             getDeliveryTypeId()        Returns the current record's "delivery_type_id" value
 * @method integer             getRoundTrip()             Returns the current record's "round_trip" value
 * @method string              getInstructions()          Returns the current record's "instructions" value
 * @method string              getSenderPhone()           Returns the current record's "sender_phone" value
 * @method string              getSenderContact()         Returns the current record's "sender_contact" value
 * @method string              getPhone()                 Returns the current record's "phone" value
 * @method string              getContact()               Returns the current record's "contact" value
 * @method string              getSignedBy()              Returns the current record's "signed_by" value
 * @method timestamp           getLastUpdated()           Returns the current record's "last_updated" value
 * @method DeliveryType        getDeliveryType()          Returns the current record's "DeliveryType" value
 * @method DeliveryType        getDeliveryType2()         Returns the current record's "DeliveryType_2" value
 * @method ServiceLevelType    getServiceLevelType()      Returns the current record's "ServiceLevelType" value
 * @method ServiceLevelType    getServiceLevelType4()     Returns the current record's "ServiceLevelType_4" value
 * @method PackageType         getPackageType()           Returns the current record's "PackageType" value
 * @method WeightType          getWeightType()            Returns the current record's "WeightType" value
 * @method ServiceLevelType    getServiceLevelType7()     Returns the current record's "ServiceLevelType_7" value
 * @method Doctrine_Collection getPackage()               Returns the current record's "Package" collection
 * @method Doctrine_Collection getPackage9()              Returns the current record's "Package_9" collection
 * @method PackageDetail       setId()                    Sets the current record's "id" value
 * @method PackageDetail       setReadyTime()             Sets the current record's "ready_time" value
 * @method PackageDetail       setReadyDate()             Sets the current record's "ready_date" value
 * @method PackageDetail       setNumPieces()             Sets the current record's "num_pieces" value
 * @method PackageDetail       setWeight()                Sets the current record's "weight" value
 * @method PackageDetail       setWeightTypeId()          Sets the current record's "weight_type_id" value
 * @method PackageDetail       setReference()             Sets the current record's "reference" value
 * @method PackageDetail       setPackageTypeId()         Sets the current record's "package_type_id" value
 * @method PackageDetail       setServiceLevelTypeId()    Sets the current record's "service_level_type_id" value
 * @method PackageDetail       setDeliveryTypeId()        Sets the current record's "delivery_type_id" value
 * @method PackageDetail       setRoundTrip()             Sets the current record's "round_trip" value
 * @method PackageDetail       setInstructions()          Sets the current record's "instructions" value
 * @method PackageDetail       setSenderPhone()           Sets the current record's "sender_phone" value
 * @method PackageDetail       setSenderContact()         Sets the current record's "sender_contact" value
 * @method PackageDetail       setPhone()                 Sets the current record's "phone" value
 * @method PackageDetail       setContact()               Sets the current record's "contact" value
 * @method PackageDetail       setSignedBy()              Sets the current record's "signed_by" value
 * @method PackageDetail       setLastUpdated()           Sets the current record's "last_updated" value
 * @method PackageDetail       setDeliveryType()          Sets the current record's "DeliveryType" value
 * @method PackageDetail       setDeliveryType2()         Sets the current record's "DeliveryType_2" value
 * @method PackageDetail       setServiceLevelType()      Sets the current record's "ServiceLevelType" value
 * @method PackageDetail       setServiceLevelType4()     Sets the current record's "ServiceLevelType_4" value
 * @method PackageDetail       setPackageType()           Sets the current record's "PackageType" value
 * @method PackageDetail       setWeightType()            Sets the current record's "WeightType" value
 * @method PackageDetail       setServiceLevelType7()     Sets the current record's "ServiceLevelType_7" value
 * @method PackageDetail       setPackage()               Sets the current record's "Package" collection
 * @method PackageDetail       setPackage9()              Sets the current record's "Package_9" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackageDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package_detail');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('ready_time', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('ready_date', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('num_pieces', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('weight', 'decimal', 7, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             'scale' => '2',
             ));
        $this->hasColumn('weight_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('reference', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('package_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('service_level_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('delivery_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('round_trip', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('instructions', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sender_phone', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('sender_contact', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('phone', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('contact', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('signed_by', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('last_updated', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeliveryType', array(
             'local' => 'delivery_type_id',
             'foreign' => 'id'));

        $this->hasOne('DeliveryType as DeliveryType_2', array(
             'local' => 'delivery_type_id',
             'foreign' => 'id'));

        $this->hasOne('ServiceLevelType', array(
             'local' => 'service_level_type_id',
             'foreign' => 'id'));

        $this->hasOne('ServiceLevelType as ServiceLevelType_4', array(
             'local' => 'service_level_type_id',
             'foreign' => 'id'));

        $this->hasOne('PackageType', array(
             'local' => 'package_type_id',
             'foreign' => 'id'));

        $this->hasOne('WeightType', array(
             'local' => 'weight_type_id',
             'foreign' => 'id'));

        $this->hasOne('ServiceLevelType as ServiceLevelType_7', array(
             'local' => 'service_level_type_id',
             'foreign' => 'id'));

        $this->hasMany('Package', array(
             'local' => 'id',
             'foreign' => 'detail_id'));

        $this->hasMany('Package as Package_9', array(
             'local' => 'id',
             'foreign' => 'detail_id'));
    }
}