<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UnableToDeliver', 'doctrine');

/**
 * BaseUnableToDeliver
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $package_data
 * @property timestamp $attempted_on
 * 
 * @method integer         getId()           Returns the current record's "id" value
 * @method string          getPackageData()  Returns the current record's "package_data" value
 * @method timestamp       getAttemptedOn()  Returns the current record's "attempted_on" value
 * @method UnableToDeliver setId()           Sets the current record's "id" value
 * @method UnableToDeliver setPackageData()  Sets the current record's "package_data" value
 * @method UnableToDeliver setAttemptedOn()  Sets the current record's "attempted_on" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnableToDeliver extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unable_to_deliver');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('package_data', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('attempted_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}