<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PackageType', 'doctrine');

/**
 * BasePackageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property Doctrine_Collection $PackageDetail
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getType()          Returns the current record's "type" value
 * @method Doctrine_Collection getPackageDetail() Returns the current record's "PackageDetail" collection
 * @method PackageType         setId()            Sets the current record's "id" value
 * @method PackageType         setType()          Sets the current record's "type" value
 * @method PackageType         setPackageDetail() Sets the current record's "PackageDetail" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePackageType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('package_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PackageDetail', array(
             'local' => 'id',
             'foreign' => 'package_type_id'));
    }
}