<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Staff', 'doctrine');

/**
 * BaseStaff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property integer $address_id
 * @property integer $client_id
 * @property Address $Address
 * @property Client $Client
 * @property Client $Client_3
 * @property Address $Address_4
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getSurname()    Returns the current record's "surname" value
 * @method integer getAddressId()  Returns the current record's "address_id" value
 * @method integer getClientId()   Returns the current record's "client_id" value
 * @method Address getAddress()    Returns the current record's "Address" value
 * @method Client  getClient()     Returns the current record's "Client" value
 * @method Client  getClient3()    Returns the current record's "Client_3" value
 * @method Address getAddress4()   Returns the current record's "Address_4" value
 * @method Staff   setId()         Sets the current record's "id" value
 * @method Staff   setName()       Sets the current record's "name" value
 * @method Staff   setSurname()    Sets the current record's "surname" value
 * @method Staff   setAddressId()  Sets the current record's "address_id" value
 * @method Staff   setClientId()   Sets the current record's "client_id" value
 * @method Staff   setAddress()    Sets the current record's "Address" value
 * @method Staff   setClient()     Sets the current record's "Client" value
 * @method Staff   setClient3()    Sets the current record's "Client_3" value
 * @method Staff   setAddress4()   Sets the current record's "Address_4" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('staff');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('surname', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('address_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('client_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Address', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Client as Client_3', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Address as Address_4', array(
             'local' => 'address_id',
             'foreign' => 'id'));
    }
}