<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PriceLevel', 'doctrine');

/**
 * BasePriceLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $courier_id
 * @property string $name
 * @property Courier $Courier
 * @property Doctrine_Collection $ServiceAddon
 * @property Doctrine_Collection $WeightPrice
 * @property Doctrine_Collection $ZonePriceLevel
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getCourierId()      Returns the current record's "courier_id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method Courier             getCourier()        Returns the current record's "Courier" value
 * @method Doctrine_Collection getServiceAddon()   Returns the current record's "ServiceAddon" collection
 * @method Doctrine_Collection getWeightPrice()    Returns the current record's "WeightPrice" collection
 * @method Doctrine_Collection getZonePriceLevel() Returns the current record's "ZonePriceLevel" collection
 * @method PriceLevel          setId()             Sets the current record's "id" value
 * @method PriceLevel          setCourierId()      Sets the current record's "courier_id" value
 * @method PriceLevel          setName()           Sets the current record's "name" value
 * @method PriceLevel          setCourier()        Sets the current record's "Courier" value
 * @method PriceLevel          setServiceAddon()   Sets the current record's "ServiceAddon" collection
 * @method PriceLevel          setWeightPrice()    Sets the current record's "WeightPrice" collection
 * @method PriceLevel          setZonePriceLevel() Sets the current record's "ZonePriceLevel" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePriceLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('price_level');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('courier_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Courier', array(
             'local' => 'courier_id',
             'foreign' => 'id'));

        $this->hasMany('ServiceAddon', array(
             'local' => 'id',
             'foreign' => 'price_level_id'));

        $this->hasMany('WeightPrice', array(
             'local' => 'id',
             'foreign' => 'price_level_id'));

        $this->hasMany('ZonePriceLevel', array(
             'local' => 'id',
             'foreign' => 'price_level_id'));
    }
}