<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CourierContact', 'doctrine');

/**
 * BaseCourierContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $courier_id
 * @property string $name
 * @property string $surname
 * @property string $telephone
 * @property string $mobile
 * @property Courier $Courier
 * @property Courier $Courier_2
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getCourierId()  Returns the current record's "courier_id" value
 * @method string         getName()       Returns the current record's "name" value
 * @method string         getSurname()    Returns the current record's "surname" value
 * @method string         getTelephone()  Returns the current record's "telephone" value
 * @method string         getMobile()     Returns the current record's "mobile" value
 * @method Courier        getCourier()    Returns the current record's "Courier" value
 * @method Courier        getCourier2()   Returns the current record's "Courier_2" value
 * @method CourierContact setId()         Sets the current record's "id" value
 * @method CourierContact setCourierId()  Sets the current record's "courier_id" value
 * @method CourierContact setName()       Sets the current record's "name" value
 * @method CourierContact setSurname()    Sets the current record's "surname" value
 * @method CourierContact setTelephone()  Sets the current record's "telephone" value
 * @method CourierContact setMobile()     Sets the current record's "mobile" value
 * @method CourierContact setCourier()    Sets the current record's "Courier" value
 * @method CourierContact setCourier2()   Sets the current record's "Courier_2" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourierContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('courier_contact');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('courier_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('surname', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 128,
             ));
        $this->hasColumn('telephone', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('mobile', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Courier', array(
             'local' => 'courier_id',
             'foreign' => 'id'));

        $this->hasOne('Courier as Courier_2', array(
             'local' => 'courier_id',
             'foreign' => 'id'));
    }
}