<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ZonePolygonType', 'doctrine');

/**
 * BaseZonePolygonType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property Doctrine_Collection $ZonePolygon
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getType()        Returns the current record's "type" value
 * @method Doctrine_Collection getZonePolygon() Returns the current record's "ZonePolygon" collection
 * @method ZonePolygonType     setId()          Sets the current record's "id" value
 * @method ZonePolygonType     setType()        Sets the current record's "type" value
 * @method ZonePolygonType     setZonePolygon() Sets the current record's "ZonePolygon" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZonePolygonType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zone_polygon_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ZonePolygon', array(
             'local' => 'id',
             'foreign' => 'type_id'));
    }
}