<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CreditCardType', 'doctrine');

/**
 * BaseCreditCardType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $abbr
 * @property integer $enabled
 * @property Doctrine_Collection $ClientPaymentDetail
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getType()                Returns the current record's "type" value
 * @method string              getAbbr()                Returns the current record's "abbr" value
 * @method integer             getEnabled()             Returns the current record's "enabled" value
 * @method Doctrine_Collection getClientPaymentDetail() Returns the current record's "ClientPaymentDetail" collection
 * @method CreditCardType      setId()                  Sets the current record's "id" value
 * @method CreditCardType      setType()                Sets the current record's "type" value
 * @method CreditCardType      setAbbr()                Sets the current record's "abbr" value
 * @method CreditCardType      setEnabled()             Sets the current record's "enabled" value
 * @method CreditCardType      setClientPaymentDetail() Sets the current record's "ClientPaymentDetail" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCreditCardType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('credit_card_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('abbr', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('enabled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ClientPaymentDetail', array(
             'local' => 'id',
             'foreign' => 'card_type_id'));
    }
}