<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SmsMessage', 'doctrine');

/**
 * BaseSmsMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $number
 * @property string $text
 * @property timestamp $sent_on
 * 
 * @method integer    getId()      Returns the current record's "id" value
 * @method string     getNumber()  Returns the current record's "number" value
 * @method string     getText()    Returns the current record's "text" value
 * @method timestamp  getSentOn()  Returns the current record's "sent_on" value
 * @method SmsMessage setId()      Sets the current record's "id" value
 * @method SmsMessage setNumber()  Sets the current record's "number" value
 * @method SmsMessage setText()    Sets the current record's "text" value
 * @method SmsMessage setSentOn()  Sets the current record's "sent_on" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmsMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sms_message');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('number', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 16,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('sent_on', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}