<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Province', 'doctrine');

/**
 * BaseProvince
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $province_territory
 * @property integer $sgc_code
 * @property string $alpha_code
 * @property string $abbreviation
 * @property Doctrine_Collection $Address
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getProvinceTerritory()  Returns the current record's "province_territory" value
 * @method integer             getSgcCode()            Returns the current record's "sgc_code" value
 * @method string              getAlphaCode()          Returns the current record's "alpha_code" value
 * @method string              getAbbreviation()       Returns the current record's "abbreviation" value
 * @method Doctrine_Collection getAddress()            Returns the current record's "Address" collection
 * @method Province            setId()                 Sets the current record's "id" value
 * @method Province            setProvinceTerritory()  Sets the current record's "province_territory" value
 * @method Province            setSgcCode()            Sets the current record's "sgc_code" value
 * @method Province            setAlphaCode()          Sets the current record's "alpha_code" value
 * @method Province            setAbbreviation()       Sets the current record's "abbreviation" value
 * @method Province            setAddress()            Sets the current record's "Address" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProvince extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('province');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('province_territory', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('sgc_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('alpha_code', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('abbreviation', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Address', array(
             'local' => 'id',
             'foreign' => 'province_id'));
    }
}