<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServiceAddon', 'doctrine');

/**
 * BaseServiceAddon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $service_level_type_id
 * @property integer $price_level_id
 * @property integer $from_zone_polygon_id
 * @property integer $to_zone_polygon_id
 * @property float $price
 * @property ServiceLevel $ServiceLevel
 * @property PriceLevel $PriceLevel
 * @property ZonePolygon $ZonePolygon
 * @property ZonePolygon $ZonePolygon_4
 * 
 * @method integer      getId()                    Returns the current record's "id" value
 * @method integer      getServiceLevelTypeId()    Returns the current record's "service_level_type_id" value
 * @method integer      getPriceLevelId()          Returns the current record's "price_level_id" value
 * @method integer      getFromZonePolygonId()     Returns the current record's "from_zone_polygon_id" value
 * @method integer      getToZonePolygonId()       Returns the current record's "to_zone_polygon_id" value
 * @method float        getPrice()                 Returns the current record's "price" value
 * @method ServiceLevel getServiceLevel()          Returns the current record's "ServiceLevel" value
 * @method PriceLevel   getPriceLevel()            Returns the current record's "PriceLevel" value
 * @method ZonePolygon  getZonePolygon()           Returns the current record's "ZonePolygon" value
 * @method ZonePolygon  getZonePolygon4()          Returns the current record's "ZonePolygon_4" value
 * @method ServiceAddon setId()                    Sets the current record's "id" value
 * @method ServiceAddon setServiceLevelTypeId()    Sets the current record's "service_level_type_id" value
 * @method ServiceAddon setPriceLevelId()          Sets the current record's "price_level_id" value
 * @method ServiceAddon setFromZonePolygonId()     Sets the current record's "from_zone_polygon_id" value
 * @method ServiceAddon setToZonePolygonId()       Sets the current record's "to_zone_polygon_id" value
 * @method ServiceAddon setPrice()                 Sets the current record's "price" value
 * @method ServiceAddon setServiceLevel()          Sets the current record's "ServiceLevel" value
 * @method ServiceAddon setPriceLevel()            Sets the current record's "PriceLevel" value
 * @method ServiceAddon setZonePolygon()           Sets the current record's "ZonePolygon" value
 * @method ServiceAddon setZonePolygon4()          Sets the current record's "ZonePolygon_4" value
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServiceAddon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service_addon');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('service_level_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('price_level_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('from_zone_polygon_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('to_zone_polygon_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('price', 'float', 7, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ServiceLevel', array(
             'local' => 'service_level_type_id',
             'foreign' => 'type_id'));

        $this->hasOne('PriceLevel', array(
             'local' => 'price_level_id',
             'foreign' => 'id'));

        $this->hasOne('ZonePolygon', array(
             'local' => 'from_zone_polygon_id',
             'foreign' => 'id'));

        $this->hasOne('ZonePolygon as ZonePolygon_4', array(
             'local' => 'to_zone_polygon_id',
             'foreign' => 'id'));
    }
}