<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Courier', 'doctrine');

/**
 * BaseCourier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_id
 * @property integer $profit_cut
 * @property integer $available
 * @property integer $enabled
 * @property Client $Client
 * @property Client $Client_2
 * @property Doctrine_Collection $CourierContact
 * @property Doctrine_Collection $CourierContact_2
 * @property Doctrine_Collection $CourierDiscount
 * @property Doctrine_Collection $CourierDiscount_2
 * @property Doctrine_Collection $Package
 * @property Doctrine_Collection $Package_10
 * @property Doctrine_Collection $PriceLevel
 * @property Doctrine_Collection $ServiceLevel
 * @property Doctrine_Collection $ServiceLevel_2
 * @property Doctrine_Collection $Surcharge
 * @property Doctrine_Collection $Surcharge_2
 * @property Doctrine_Collection $Zone
 * @property Doctrine_Collection $Zone_2
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method integer             getClientId()          Returns the current record's "client_id" value
 * @method integer             getProfitCut()         Returns the current record's "profit_cut" value
 * @method integer             getAvailable()         Returns the current record's "available" value
 * @method integer             getEnabled()           Returns the current record's "enabled" value
 * @method Client              getClient()            Returns the current record's "Client" value
 * @method Client              getClient2()           Returns the current record's "Client_2" value
 * @method Doctrine_Collection getCourierContact()    Returns the current record's "CourierContact" collection
 * @method Doctrine_Collection getCourierContact2()   Returns the current record's "CourierContact_2" collection
 * @method Doctrine_Collection getCourierDiscount()   Returns the current record's "CourierDiscount" collection
 * @method Doctrine_Collection getCourierDiscount2()  Returns the current record's "CourierDiscount_2" collection
 * @method Doctrine_Collection getPackage()           Returns the current record's "Package" collection
 * @method Doctrine_Collection getPackage10()         Returns the current record's "Package_10" collection
 * @method Doctrine_Collection getPriceLevel()        Returns the current record's "PriceLevel" collection
 * @method Doctrine_Collection getServiceLevel()      Returns the current record's "ServiceLevel" collection
 * @method Doctrine_Collection getServiceLevel2()     Returns the current record's "ServiceLevel_2" collection
 * @method Doctrine_Collection getSurcharge()         Returns the current record's "Surcharge" collection
 * @method Doctrine_Collection getSurcharge2()        Returns the current record's "Surcharge_2" collection
 * @method Doctrine_Collection getZone()              Returns the current record's "Zone" collection
 * @method Doctrine_Collection getZone2()             Returns the current record's "Zone_2" collection
 * @method Courier             setId()                Sets the current record's "id" value
 * @method Courier             setClientId()          Sets the current record's "client_id" value
 * @method Courier             setProfitCut()         Sets the current record's "profit_cut" value
 * @method Courier             setAvailable()         Sets the current record's "available" value
 * @method Courier             setEnabled()           Sets the current record's "enabled" value
 * @method Courier             setClient()            Sets the current record's "Client" value
 * @method Courier             setClient2()           Sets the current record's "Client_2" value
 * @method Courier             setCourierContact()    Sets the current record's "CourierContact" collection
 * @method Courier             setCourierContact2()   Sets the current record's "CourierContact_2" collection
 * @method Courier             setCourierDiscount()   Sets the current record's "CourierDiscount" collection
 * @method Courier             setCourierDiscount2()  Sets the current record's "CourierDiscount_2" collection
 * @method Courier             setPackage()           Sets the current record's "Package" collection
 * @method Courier             setPackage10()         Sets the current record's "Package_10" collection
 * @method Courier             setPriceLevel()        Sets the current record's "PriceLevel" collection
 * @method Courier             setServiceLevel()      Sets the current record's "ServiceLevel" collection
 * @method Courier             setServiceLevel2()     Sets the current record's "ServiceLevel_2" collection
 * @method Courier             setSurcharge()         Sets the current record's "Surcharge" collection
 * @method Courier             setSurcharge2()        Sets the current record's "Surcharge_2" collection
 * @method Courier             setZone()              Sets the current record's "Zone" collection
 * @method Courier             setZone2()             Sets the current record's "Zone_2" collection
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('courier');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('client_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('profit_cut', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('available', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('enabled', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Client as Client_2', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasMany('CourierContact', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('CourierContact as CourierContact_2', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('CourierDiscount', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('CourierDiscount as CourierDiscount_2', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('Package', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('Package as Package_10', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('PriceLevel', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('ServiceLevel', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('ServiceLevel as ServiceLevel_2', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('Surcharge', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('Surcharge as Surcharge_2', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('Zone', array(
             'local' => 'id',
             'foreign' => 'courier_id'));

        $this->hasMany('Zone as Zone_2', array(
             'local' => 'id',
             'foreign' => 'courier_id'));
    }
}