<?php

/**
 * PackageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cexp
 * @subpackage model
 * @author     Courier Express Development
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class PackageType extends BasePackageType
{
}
