<?php

/**
 * UnableToDeliverTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnableToDeliverTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnableToDeliverTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnableToDeliver');
    }
}