INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Alabama","AL","Ala.",1);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Alaska","AK","~",2);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Arizona","AZ","Ariz.",4);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Arkansas","AR","Ark.",5);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("California","CA","Calif.",6);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Colorado","CO","Colo.",8);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Connecticut","CT","Conn.",9);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Delaware","DE","Del.",10);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("District of Columbia","DC","D.C.",11);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Florida","FL","Fla.",12);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Georgia","GA","Ga.",13);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Hawaii","HI","~",15);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Idaho","ID","~",16);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Illinois","IL","Ill.",17);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Indiana","IN","Ind.",18);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Iowa","IA","~",19);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Kansas","KS","Kans.",20);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Kentucky","KY","Ky.",21);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Louisiana","LA","~",22);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Maine","ME","Me.",23);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Maryland","MD","Md.",24);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Massachusetts","MA","Mass.",25);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Michigan","MI","Mich.",26);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Minnesota","MN","Minn.",27);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Mississippi","MS","Miss.",28);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Missouri","MO","Mo.",29);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Montana","MT","Mont.",30);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Nebraska","NE","Nebr.",31);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Nevada","NV","Nev.",32);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("New Hampshire","NH","N.H.",33);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("New Jersey","NJ","N.J.",34);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("New Mexico","NM","N.Mex.",35);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("New York","NY","N.Y.",36);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("North Carolina","NC","N.C.",37);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("North Dakota","ND","~",38);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Ohio","OH","~",39);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Oklahoma","OK","Okla.",40);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Oregon","OR","Ore.",41);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Pennsylvania","PA","Penn.",42);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Rhode Island","RI","R.I.",44);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("South Carolina","SC","S.C.",45);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("South Dakota","SD","~",46);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Tennessee","TN","Tenn.",47);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Texas","TX","Tex.",48);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Utah","UT","~",49);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Vermont","VT","Vt.",50);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Virginia","VA","Va.",51);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Washington","WA","Wash.",53);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("West Virginia","WV","W.Va.",54);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Wisconsin","WI","Wis.",55);
INSERT INTO state (name,alpha_code,abbreviation,numerical_code) VALUES ("Wyoming","WY","Wyo.",56);
